//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryStreamCustomerWinServ.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.66\\sql2008;Initial Catalog=Ascend_Chris;Persist Security In" +
            "fo=True;User ID=sa;Password=fsww")]
        public string Ascend_Demo_408_2008ConnectionString {
            get {
                return ((string)(this["Ascend_Demo_408_2008ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.66\\sql2008;Initial Catalog=Ascend_Chris;Persist Security In" +
            "fo=True;User ID=sa;Password=fsww")]
        public string AScendCloud02ConnectionString {
            get {
                return ((string)(this["AScendCloud02ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.66\\sql2008;Initial Catalog=Ascend_Chris;Persist Security In" +
            "fo=True;User ID=sa;Password=fsww")]
        public string Ascend_Demo_408_2008ConnectionString1 {
            get {
                return ((string)(this["Ascend_Demo_408_2008ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.2.66\\sql2008;Initial Catalog=Ascend_Chris;Persist Security In" +
            "fo=True;User ID=sa;Password=fsww")]
        public string Ascend_Demo_408_20081ConnectionString {
            get {
                return ((string)(this["Ascend_Demo_408_20081ConnectionString"]));
            }
        }
    }
}
